version: '3.8'

services:
  postgres:
    image: postgres:15.3-alpine3.18
    container_name: rinha-postgres
    command: '-c shared_buffers=256MB -c max_connections=200'
    environment:
      - 'POSTGRES_DB=rinha_dev'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'LANG=en_US.utf8'
    volumes:
      - './priv/repo/structure.sql:/docker-entrypoint-initdb.d/ddl.sql'
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.45'
          memory: 864M
        reservations:
          cpus: '0.10'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s

  api1:
    image: 'ghcr.io/rwillians/rinha-backend--elixir-cowboy-ecto:${IMAGE_TAG:-latest}'
    container_name: rinha-backend-api1
    depends_on:
      - postgres
    environment:
      - 'DATABASE_URL=postgres://postgres:postgres@postgres/rinha_dev'
      - 'RELEASE_COOKIE=4F022BFB13DB6D12BDB7818F80AC2B6F'
      - 'RELEASE_DISTRIBUTION=sname'
      - 'SERVER_ENABLED=true'
      - 'POOL_SIZE=100'
    entrypoint: [ "sh", "-c" ]
    #                   ↓ Demora alguns segundos para o banco de dados ficar
    #                   ↓ disponível então precisamos esperar um pouco.
    command: [ 'busybox sleep 10s && echo "starting http server..." && _build/prod/rel/rinha/bin/rinha start' ]
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.425'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s

  api2:
    image: 'ghcr.io/rwillians/rinha-backend--elixir-cowboy-ecto:${IMAGE_TAG:-latest}'
    container_name: rinha-backend-api2
    depends_on:
      - postgres
    environment:
      - 'DATABASE_URL=postgres://postgres:postgres@postgres/rinha_dev'
      - 'RELEASE_COOKIE=4F022BFB13DB6D12BDB7818F80AC2B6F'
      - 'RELEASE_DISTRIBUTION=sname'
      - 'SERVER_ENABLED=true'
      - 'POOL_SIZE=100'
    entrypoint: [ "sh", "-c" ]
    #                   ↓ Demora alguns segundos para o banco de dados ficar
    #                   ↓ disponível então precisamos esperar um pouco.
    command: [ 'busybox sleep 10s && echo "starting http server..." && _build/prod/rel/rinha/bin/rinha start' ]
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.425'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s

  nginx:
    image: nginx:1.25.1-alpine3.17-slim
    container_name: rwillians-ngnix
    volumes:
      - '.data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    depends_on:
      - api1
      - api2
    ports:
      - '${PORT:-8080}:8080'
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.20'
          memory: 96M
        reservations:
          cpus: '0.05'
          memory: 16M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
