name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'mix.exs'
      - 'mix.lock'
      - 'config/*.exs'
      - 'lib/**/*.ex'
      - 'lib/**/*.eex'
      - 'priv/repo/structure.sql'
      - 'test/**.ex'
      - 'test/**.exs'
    branches:
      - main

env:
  ELIXIR_VERSION: '1.15.4'
  OTP_VERSION: '26.0.2'
  MIX_ENV: test

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    concurrency:
      group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
      cancel-in-progress: true

    services:
      db:
        image: postgres:15.3-alpine3.18
        env:
          POSTGRES_DB: rinha_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/rinha_test?ssl=false&pool_size=10

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup elixir-${{ env.ELIXIR_VERSION }} otp-${{ env.OTP_VERSION }}
        uses: erlef/setup-elixir@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Retrieve dependencies cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        id: deps-cache
        with:
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-${{ secrets.CACHE_VERSION }}
          path: |
            deps/
            _build/test/
            !_build/test/lib/rinha

      - name: Install and compile dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix do deps.get --only=test, deps.compile

      - name: Retrieve build cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        id: build-cache
        with:
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-api-${{ secrets.CACHE_VERSION }}
          path: |
            _build/test/lib/rinha

      - name: Compile app
        run: mix compile --no-deps-check --return-errors --all-warnings --warnings-as-errors

      - name: Load database structure
        run: mix ecto.load

      - name: Run tests
        run: mix test --max-failures=1
